apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    team: medlemskap
    app: medlemskap-oppslag-funksjonelle-tester
  name: medlemskap-oppslag-funksjonelle-tester
  namespace: medlemskap
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: medlemskap
      podSelector:
        matchLabels:
          app: medlemskap-oppslag
    - namespaceSelector:
        matchLabels:
          linkerd.io/is-control-plane: "true"
    - namespaceSelector: { }
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.6.0.0/15
        - 172.16.0.0/12
        - 192.168.0.0/16
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: medlemskap
          podSelector:
            matchLabels:
              app: medlemskap-oppslag
    - from:
      - namespaceSelector:
          matchLabels:
            name: nais
        podSelector:
          matchLabels:
            app: prometheus
    - from:
      - namespaceSelector:
          matchLabels:
            linkerd.io/is-control-plane: "true"
    - from:
      - namespaceSelector:
          matchLabels:
            linkerd.io/extension: viz
        podSelector:
          matchLabels:
            component: tap
    - from:
      - namespaceSelector:
          matchLabels:
            linkerd.io/extension: viz
        podSelector:
          matchLabels:
            component: prometheus
  podSelector:
    matchLabels:
      app: medlemskap-oppslag-funksjonelle-tester
  policyTypes:
    - Ingress
    - Egress
