apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  labels:
    team: medlemskap
    app: medlemskap-oppslag-funksjonelle-tester
  name: medlemskap-oppslag-funksjonelle-tester
  namespace: medlemskap
spec:
  exportTo:
    - .
  hosts:
    - api-gw-q1.oera.no
    - login.microsoftonline.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS