apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: medlemskap-oppslag-funksjonelle-tester
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  accessPolicy:
    outbound:
      rules:
        application: medlemskap-oppslag
  activeDeadlineSeconds: 150
  azure:
    application:
      enabled: true
  backoffLimit: 2
  completions: 1
  env:
    - name: MEDLEMSKAP_BASE_URL
      value: http://medlemskap-oppslag
    - name: LINKERD_SIDECAR_BASE_URL
      value: http://localhost:4191
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://api-gw-q1.oera.no/security-token-service
    - name: CUCUMBER_ENV
      value: dev
  envFrom:
    - secretRef:
        name: medlemskap-oppslag-funksjonelle-tester-secrets
  restartPolicy: Never
  ttlSecondsAfterFinished: 400