apiVersion: batch/v1
kind: Job
metadata:
  name: medlemskap-oppslag-funksjonelle-tester
  namespace: medlemskap
  labels:
    team: medlemskap
    app: medlemskap-oppslag-funksjonelle-tester
    jobcreator: {{app}}
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 600
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        team: medlemskap
        app: medlemskap-oppslag-funksjonelle-tester
        jobcreator: {{app}}
    spec:
      ttlSecondsAfterFinished: 600
      imagePullSecrets:
        - name: gpr-credentials
      serviceAccountName: default
      restartPolicy: Never
      initContainers:
        - name: vks-init
          image: navikt/vault-sidekick:v0.3.10-d122b16
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          args:
            - -v=10
            - -logtostderr
            - -vault=https://vault.adeo.no
            - -save-token=/var/run/secrets/nais.io/vault/vault_token
            - -one-shot
            - -cn=secret:serviceuser/data/dev/srvmedlemskap-ft:dir=/var/run/secrets/nais.io/service_user,fmt=flatten
            #- -cn=secret:secret/medlemskap/testdata/fnr/:dir=/var/run/secrets/nais.io/test_data,fmt=flatten
          env:
            - name: NAV_TRUSTSTORE_PATH
              value: /etc/ssl/certs/java/cacerts
            - name: NAV_TRUSTSTORE_PASSWORD
              value: changeme
            - name: VAULT_AUTH_METHOD
              value: kubernetes
            - name: VAULT_SIDEKICK_ROLE
              value: medlemskap-oppslag-funksjonelle-tester
            - name: VAULT_K8S_LOGIN_PATH
              value: auth/kubernetes/preprod/fss/login
          volumeMounts:
            - mountPath: /var/run/secrets/nais.io/vault
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/vault
            - mountPath: /var/run/secrets/nais.io/service_user
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/service_user
            # - mountPath: /var/run/secrets/nais.io/test_data
            #   name: vault-secrets
            #   subPath: subpath/var/run/secrets/nais.io/test_data
      containers:
        - name: medlemskap-oppslag-funksjonelle-tester
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          env:
            - name: AZURE_TENANT
              value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
            - name: AZURE_AUTHORITY_ENDPOINT
              value: https://login.microsoftonline.com
            - name: CUCUMBER_ENV
              value: dev
            - name: NAV_TRUSTSTORE_PATH
              value: /etc/ssl/certs/java/cacerts
            - name: NAV_TRUSTSTORE_PASSWORD
              value: changeme
          image: {{image}}
          azure:
            application:
              enabled: true
            webproxy: true
          imagePullPolicy: Always
      volumes:
        - name: vault-secrets
          emptyDir:
            medium: Memory
