apiVersion: batch/v1
kind: Job
metadata:
  name: medlemskap-oppslag-funksjonelle-tester
  namespace: medlemskap
  labels:
    team: medlemskap
    app: medlemskap-oppslag-funksjonelle-tester
    jobcreator: medlemskap-oppslag-funksjonelle-tester
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 600
  activeDeadlineSeconds: 300
  restartPolicy: Never
  template:
    metadata:
      labels:
        team: medlemskap
        app: medlemskap-oppslag-funksjonelle-tester
        jobcreator: {{app}}
    spec:
      ttlSecondsAfterFinished: 600
      imagePullSecrets:
        - name: gpr-credentials
      serviceAccountName: default
      restartPolicy: Never

      containers:
        - name: medlemskap-oppslag-funksjonelle-tester
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          env:
            - name: AZURE_TENANT
              value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
            - name: AZURE_AUTHORITY_ENDPOINT
              value: https://login.microsoftonline.com
            - name: MEDLEMSKAP_BASE_URL
              value: https://medlemskap-oppslag.dev.intern.nav.no
            - name: AZURE_MEDLEMSKAP_ID
              value: 496b0ded-cfdb-4430-b7b6-b568504de005
            - name: SECURITY_TOKEN_SERVICE_REST_URL
              value: https://api-gw-q1.oera.no/security-token-service
            - name: CUCUMBER_ENV
              value: dev
            - name: NAV_TRUSTSTORE_PATH
              value: /etc/ssl/certs/java/cacerts
            - name: NAV_TRUSTSTORE_PASSWORD
              value: changeme
            - name: HTTP_PROXY
              value: http://webproxy.nais:8088
            - name: http_proxy
              value: http://webproxy.nais:8088
            - name: HTTPS_PROXY
              value: http://webproxy.nais:8088
            - name: https_proxy
              value: http://webproxy.nais:8088
            - name: NO_PROXY
              value: localhost,127.0.0.1,10.254.0.1,.local,.adeo.no,.nav.no,.aetat.no,.devillo.no,.oera.no,.nais.io
            - name: no_proxy
              value: localhost,127.0.0.1,10.254.0.1,.local,.adeo.no,.nav.no,.aetat.no,.devillo.no,.oera.no,.nais.io
            - name: JAVA_PROXY_OPTIONS
              value: -Dhttp.proxyHost=webproxy.nais -Dhttps.proxyHost=webproxy.nais -Dhttp.proxyPort=8088 -Dhttps.proxyPort=8088 -Dhttp.nonProxyHosts=localhost|127.0.0.1|10.254.0.1|*.local|*.adeo.no|*.nav.no|*.aetat.no|*.devillo.no|*.oera.no|*.nais.io
          envFrom:
            - secretRef:
                name: medlemskap-oppslag-funksjonelle-tester
          image: {{image}}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/ssl/certs/ca-certificates.crt
              name: ca-bundle-pem
              readOnly: true
              subPath: ca-bundle.pem
            - mountPath: /etc/pki/tls/certs/ca-bundle.crt
              name: ca-bundle-pem
              readOnly: true
              subPath: ca-bundle.pem
            - mountPath: /etc/ssl/ca-bundle.pem
              name: ca-bundle-pem
              readOnly: true
              subPath: ca-bundle.pem
            - mountPath: /etc/pki/tls/cacert.pem
              name: ca-bundle-pem
              readOnly: true
              subPath: ca-bundle.pem
            - mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
              name: ca-bundle-pem
              readOnly: true
              subPath: ca-bundle.pem
            - mountPath: /etc/ssl/certs/java/cacerts
              name: ca-bundle-jks
              readOnly: true
              subPath: ca-bundle.jks
      volumes:
        - name: ca-bundle-pem
          configMap:
            defaultMode: 420
            name: ca-bundle-pem
        - name: ca-bundle-jks
          configMap:
            defaultMode: 420
            name: ca-bundle-jks