name: Build and deploy

on: [push]

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/medlemskap-oppslag-funksjonelle-tester:${{ github.sha }}
jobs:
  build:
    name: Build tests, package tests in docker image and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java 13
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Cache gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build --info
      - name: Build and Publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t $IMAGE .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push $IMAGE
      - name: Upload testjob.yaml
        uses: actions/upload-artifact@v1
        with:
          name: job-yaml
          path: nais
  run:
    name: Run tests as a Job
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch job yml
        uses: actions/download-artifact@v1
        with:
          name: job-yaml
          path: nais
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/tests.yml
          PRINT_PAYLOAD: true
          VAR: app=medlemskap-oppslag-funksjonelle-tester
        timeout-minutes: 5
